<a href="https://colab.research.google.com/github/yuval728/MLOA/blob/main/MLOAExp3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd
import numpy as np

In [6]:
#Q1
def solve(A, n):

    dp = [[0 for i in range(2000)] for i in range(2000)]
    flag = 1

    sum = 0
    for i in range(n):
        sum += A[i]

    for i in range(-sum, sum+1):
        dp[0][i] = 10**9

    # Base Case
    dp[0][0] = 0

    for i in range(1, n+1):
        for j in range(-sum, sum+1):
            dp[flag][j] = 10**9
            if (j - A[i - 1] <= sum and j - A[i - 1] >= -sum):
                dp[flag][j] = dp[flag ^ 1][j - A[i - 1]]
            if (j + A[i - 1] <= sum
                and j + A[i - 1] >= -sum
                    and dp[flag ^ 1][j + A[i - 1]] != 10**9):
                dp[flag][j] = min(dp[flag][j],
                                  dp[flag ^ 1][j + A[i - 1]] + 1)

        flag = flag ^ 1

    for i in range(sum+1):
        if (dp[flag ^ 1][i] != 10**9):
            return dp[flag ^ 1][i]

    return n - 1


arr =  np.random.randint(100,size=(5))  #[10, 22, 9, 33, 21, 50, 41, 60]
n = len(arr)
print(arr)
print(solve(arr, n))

[91 87 93 88 60]
2


In [4]:
#Q2
n,m=3,5
grid = np.random.randint(10, size=(n,m))
# path=np.zeros((n,m))
results=[]
def maxDist(i,j,sum=0):
  if i==0 and j==m-1:
    return sum
  if 0<=i and 0<=j<m:
    temp=0
    if i!=0:
      if grid[i][j]>grid[i-1][j]:
        temp=grid[i][j]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
#Q3
arr=np.random.randint(10,size=(5))
print(arr)
r=arr[0]
n=arr[1]
if arr[1]<arr[0]:
  r=arr[1]
  n=arr[0]

def factorial(n):
    return np.prod(range(1,n+1))

for i in range(2,len(arr)):
  if n<arr[i]:
    r=n
    n=arr[i]
  elif r<arr[i]:
    r=arr[i]
print(n,r)
print(factorial(n)/(factorial(n-r)))

[7 5 8 0 1]
8 7
40320.0


In [23]:
#Q4
arr=[1, 2, 1, 4, 3]

def getMinOps(ar):
    n = len(ar)

    small = min(ar)
    large = max(ar)

    dp = [[ 0 for i in range(large + 1)]
              for i in range(n)]

    # Fill the dp[]][ array for base cases
    for j in range(small, large + 1):
        dp[0][j] = abs(ar[0] - j)


    for i in range(1, n):
        minimum = 10**9
        for j in range(small, large + 1):
          minimum = min(minimum, dp[i - 1][j])
          dp[i][j] = minimum + abs(ar[i] - j)

    ans = 10**9
    for j in range(small, large + 1):
        ans = min(ans, dp[n - 1][j])

    return ans
print(arr)
getMinOps(arr)


[1, 2, 1, 4, 3]


2