<a href="https://colab.research.google.com/github/yuval728/MLOA/blob/main/MLOAExp3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Yuval Mehta C057
#Div-B Sem-X
#Exp3 MLOA

In [3]:
import pandas as pd
import numpy as np

In [6]:
#Q1
def solve(A, n):

    dp = [[0 for i in range(2000)] for i in range(2000)]
    flag = 1

    sum = 0
    for i in range(n):
        sum += A[i]

    for i in range(-sum, sum+1):
        dp[0][i] = 10**9

    # Base Case
    dp[0][0] = 0

    for i in range(1, n+1):
        for j in range(-sum, sum+1):
            dp[flag][j] = 10**9
            if (j - A[i - 1] <= sum and j - A[i - 1] >= -sum):
                dp[flag][j] = dp[flag ^ 1][j - A[i - 1]]
            if (j + A[i - 1] <= sum
                and j + A[i - 1] >= -sum
                    and dp[flag ^ 1][j + A[i - 1]] != 10**9):
                dp[flag][j] = min(dp[flag][j],
                                  dp[flag ^ 1][j + A[i - 1]] + 1)

        flag = flag ^ 1

    for i in range(sum+1):
        if (dp[flag ^ 1][i] != 10**9):
            return dp[flag ^ 1][i]

    return n - 1


arr =  np.random.randint(100,size=(5))  #[10, 22, 9, 33, 21, 50, 41, 60]
n = len(arr)
print(arr)
print(solve(arr, n))

[91 87 93 88 60]
2


In [6]:
#Q2
n,m=3,5
grid = np.random.randint(10, size=(n,m))
path=np.zeros((n,m))

path[n-1][0]=grid[n-1][0]
def maxDist():
  for i in range(n-2,-1,-1):
    path[i][0]=path[i+1][0]+grid[i][0]
  for j in range(1, m):
        path[n - 1][j] = path[n - 1][j - 1] + grid[n - 1][j]
  for i in range(n-2,-1,-1):
    for j in range(1,m):
      path[i][j]=max(path[i+1][j],path[i][j-1])+grid[i][j]
      
  print("path:\n",path)
  return path[0][m-1]

print("Grid:\n",grid)
print(maxDist())  
  
    

Grid:
 [[9 9 5 1 2]
 [1 0 2 3 2]
 [6 3 7 2 5]]
path:
 [[16. 25. 30. 31. 33.]
 [ 7.  9. 18. 21. 25.]
 [ 6.  9. 16. 18. 23.]]
33.0


In [16]:
#Q3
arr=np.random.randint(10,size=(5))
print(arr)
r=arr[0]
n=arr[1]
if arr[1]<arr[0]:
  r=arr[1]
  n=arr[0]

def factorial(n):
    return np.prod(range(1,n+1))

for i in range(2,len(arr)):
  if n<arr[i]:
    r=n
    n=arr[i]
  elif r<arr[i]:
    r=arr[i]
print(n,r)
print(factorial(n)/(factorial(n-r)))

[7 5 8 0 1]
8 7
40320.0


In [23]:
#Q4
arr=[1, 2, 1, 4, 3]

def getMinOps(ar):
    n = len(ar)

    small = min(ar)
    large = max(ar)

    dp = [[ 0 for i in range(large + 1)]
              for i in range(n)]

    # Fill the dp[]][ array for base cases
    for j in range(small, large + 1):
        dp[0][j] = abs(ar[0] - j)


    for i in range(1, n):
        minimum = 10**9
        for j in range(small, large + 1):
          minimum = min(minimum, dp[i - 1][j])
          dp[i][j] = minimum + abs(ar[i] - j)

    ans = 10**9
    for j in range(small, large + 1):
        ans = min(ans, dp[n - 1][j])

    return ans
print(arr)
getMinOps(arr)


[1, 2, 1, 4, 3]


2

**Observation and Learning**

Matrix operations provide a powerful framework for manipulating data, enabling efficient computations and transformations. The ability to find the minimum cost path in various scenarios, such as network routing or graph traversal, facilitates optimal decision-making processes. Similarly, identifying the maximum value in an integer array is fundamental in data analysis, statistics, and algorithmic design.










**Conclusion**

In conclusion, the diverse applications of matrix operations, minimum cost path finding, maximum value identification in an integer array, and array sorting underscore the versatility and significance of these computational techniques.