In [ ]:
#Yuval Mehta C057
#Div-B Sem-X
#Exp5 MLOA

In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [2]:
df=pd.read_csv("data.csv")

df.head()

date      price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0  2014-05-02 00:00:00   313000.0       3.0       1.50         1340      7912   
1  2014-05-02 00:00:00  2384000.0       5.0       2.50         3650      9050   
2  2014-05-02 00:00:00   342000.0       3.0       2.00         1930     11947   
3  2014-05-02 00:00:00   420000.0       3.0       2.25         2000      8030   
4  2014-05-02 00:00:00   550000.0       4.0       2.50         1940     10500   

   floors  waterfront  view  condition  sqft_above  sqft_basement  yr_built  \
0     1.5           0     0          3        1340              0      1955   
1     2.0           0     4          5        3370            280      1921   
2     1.0           0     0          4        1930              0      1966   
3     1.0           0     0          4        1000           1000      1963   
4     1.0           0     0          4        1140            800      1976   

   yr_renovated                    street       city  statezip country  
0          2005      18810 Densmore Ave N  Shoreline  WA 98133     USA  
1             0           709 W Blaine St    Seattle  WA 98119     USA  
2             0  26206-26214 143rd Ave SE       Kent  WA 98042     USA  
3             0           857 170th Pl NE   Bellevue  WA 98008     USA  
4          1992         9105 170th Ave NE    Redmond  WA 98052     USA

In [3]:
df.drop(columns=['date','country','yr_renovated','street','city','statezip'],inplace=True)

In [4]:
df['total_sqft']=df.sqft_lot+df.sqft_above+df.sqft_basement+df.sqft_living
df

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
0     3.130000e+05       3.0       1.50         1340      7912     1.5   
1     2.384000e+06       5.0       2.50         3650      9050     2.0   
2     3.420000e+05       3.0       2.00         1930     11947     1.0   
3     4.200000e+05       3.0       2.25         2000      8030     1.0   
4     5.500000e+05       4.0       2.50         1940     10500     1.0   
...            ...       ...        ...          ...       ...     ...   
4595  3.081667e+05       3.0       1.75         1510      6360     1.0   
4596  5.343333e+05       3.0       2.50         1460      7573     2.0   
4597  4.169042e+05       3.0       2.50         3010      7014     2.0   
4598  2.034000e+05       4.0       2.00         2090      6630     1.0   
4599  2.206000e+05       3.0       2.50         1490      8102     2.0   

      waterfront  view  condition  sqft_above  sqft_basement  yr_built  \
0              0     0          3        1340              0      1955   
1              0     4          5        3370            280      1921   
2              0     0          4        1930              0      1966   
3              0     0          4        1000           1000      1963   
4              0     0          4        1140            800      1976   
...          ...   ...        ...         ...            ...       ...   
4595           0     0          4        1510              0      1954   
4596           0     0          3        1460              0      1983   
4597           0     0          3        3010              0      2009   
4598           0     0          3        1070           1020      1974   
4599           0     0          4        1490              0      1990   

      total_sqft  
0          10592  
1          16350  
2          15807  
3          12030  
4          14380  
...          ...  
4595        9380  
4596       10493  
4597       13034  
4598       10810  
4599       11082  

[4600 rows x 13 columns]

In [5]:
features=df.columns[1:-1]
features

Index(['bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
       'waterfront', 'view', 'condition', 'sqft_above', 'sqft_basement',
       'yr_built'],
      dtype='object')

In [6]:
X=df[features]
y=df.price


In [7]:
np.array(X)


array([[3.000e+00, 1.500e+00, 1.340e+03, ..., 1.340e+03, 0.000e+00,
        1.955e+03],
       [5.000e+00, 2.500e+00, 3.650e+03, ..., 3.370e+03, 2.800e+02,
        1.921e+03],
       [3.000e+00, 2.000e+00, 1.930e+03, ..., 1.930e+03, 0.000e+00,
        1.966e+03],
       ...,
       [3.000e+00, 2.500e+00, 3.010e+03, ..., 3.010e+03, 0.000e+00,
        2.009e+03],
       [4.000e+00, 2.000e+00, 2.090e+03, ..., 1.070e+03, 1.020e+03,
        1.974e+03],
       [3.000e+00, 2.500e+00, 1.490e+03, ..., 1.490e+03, 0.000e+00,
        1.990e+03]])

In [8]:
matX=np.array([np.ones(len(df)), X.bedrooms,X.bathrooms,X.sqft_living,X.sqft_lot,X.floors,X.waterfront,X.view,X.condition,X.sqft_above,X.sqft_basement])
matX.T

array([[1.00e+00, 3.00e+00, 1.50e+00, ..., 3.00e+00, 1.34e+03, 0.00e+00],
       [1.00e+00, 5.00e+00, 2.50e+00, ..., 5.00e+00, 3.37e+03, 2.80e+02],
       [1.00e+00, 3.00e+00, 2.00e+00, ..., 4.00e+00, 1.93e+03, 0.00e+00],
       ...,
       [1.00e+00, 3.00e+00, 2.50e+00, ..., 3.00e+00, 3.01e+03, 0.00e+00],
       [1.00e+00, 4.00e+00, 2.00e+00, ..., 3.00e+00, 1.07e+03, 1.02e+03],
       [1.00e+00, 3.00e+00, 2.50e+00, ..., 4.00e+00, 1.49e+03, 0.00e+00]])

In [9]:
coeff=(np.matmul(np.linalg.inv(np.matmul(matX,matX.T)),np.matmul(matX,y)))

coeff

array([ 2.13895442e+06,  6.22230066e+05, -8.01798946e+05, -1.02400000e+03,
        4.46899468e-01, -1.14048462e+04,  3.90378423e+05,  4.55933882e+04,
        8.21831355e+04,  1.02400000e+03,  1.02400000e+03])

In [10]:
mpreds=coeff[0]+(coeff[1]*X.bedrooms)+(coeff[2]*X.bathrooms)+(coeff[3]*X.sqft_living)+(coeff[4]*X.sqft_lot)+(coeff[5]*X.floors)+(coeff[6]*X.waterfront)+(coeff[7]*X.view)+(coeff[8]*X.condition)+(coeff[9]*X.sqft_above)+(coeff[10]*X.sqft_basement)
mpreds

0       3.035924e+06
1       3.820131e+06
2       2.724714e+06
3       2.522513e+06
4       2.945397e+06
            ...     
4595    2.922666e+06
4596    2.228271e+06
4597    2.228022e+06
4598    3.262384e+06
4599    2.310691e+06
Length: 4600, dtype: float64

In [11]:
print(mean_squared_error(y,mpreds))
print(mean_absolute_error(y,mpreds))

5838577075329.961
2287566.534721665


In [83]:
from sklearn.linear_model import Lasso

l1=Lasso(alpha=7)


In [84]:
l1.fit(X,y)

c:\Users\Yuval\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.255e+14, tolerance: 1.462e+11
  model = cd_fast.enet_coordinate_descent(


Lasso(alpha=7)

In [85]:
print(l1.intercept_)
print(l1.coef_)

4772465.2123675905
[-5.77272273e+04  5.66768141e+04  2.70467641e+02 -6.92481393e-01
  3.80343683e+04  3.53791535e+05  4.59583937e+04  2.80798096e+04
 -8.80835006e+00 -3.84275831e+01 -2.46344900e+03]


In [86]:
l1preds=l1.predict(X)

In [87]:
print(mean_squared_error(y,l1preds))
print(mean_absolute_error(y,l1preds))

248646308105.19293
168761.70470529006


In [96]:
from sklearn.linear_model import Ridge

l2=Ridge(alpha=10)

In [97]:
l2.fit(X,y)

Ridge(alpha=10)

In [98]:
print(l2.intercept_)
print(l2.coef_)

4779498.111731302
[-5.80550918e+04  5.62670849e+04  1.64898341e+02 -6.96417936e-01
  3.77084043e+04  2.62928290e+05  4.93229421e+04  2.76917224e+04
  9.74846882e+01  6.74137328e+01 -2.46583729e+03]


In [99]:
l2preds=l2.predict(X)
 
print(mean_squared_error(y,l2preds))
print(mean_absolute_error(y,l2preds))

248698560112.0238
168806.4330894579


**Observation and Learning**
Lasso (L1 regularization):
Promotes sparsity by setting some coefficients to zero.
Facilitates feature selection.
Suitable for high-dimensional datasets and when feature interpretation is important.
More computationally intensive than Ridge due to absolute value of coefficients.
Lasso for feature selection and interpreting models.

Ridge (L2 regularization):
Shrinks coefficients towards zero but never exactly to zero.
Retains all features, albeit with reduced magnitude.
Better handles multicollinearity.
Less computationally intensive compared to Lasso.
Ridge when multicollinearity is present and all features are assumed relevant.

**Conclusion**
In conclusion, Lasso regularization prioritizes sparsity and feature selection, making it ideal for interpretable models in high-dimensional datasets. Ridge regularization, focusing on coefficient shrinkage without feature elimination, suits scenarios with multicollinearity and when all features are relevant. Understanding their trade-offs helps choose the right technique for better model performance and interpretability.